### ISSUE TITLE
JSBox在启动后是否会扫描全部文件？能否添加某个标记让JSBox避开扫描某个文件夹？

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#1]
经过我的测试，JSBox内如果有一个文件比较多的文件夹（10万个以上），那么在JSBox启动后、打开包含此文件夹的App、打开此文件夹上面任意一级文件夹，都会出现极为明显的卡顿。
在我的测试中，添加一个包含35万张图片的文件夹后，JSBox中进行上面任何一步操作，都需要先等待一分半钟以上，这对性能是极大的影响。
能否加入一个标记功能，使得JSBox对被标记的文件夹“视而不见”，从而避免文件多了造成的卡顿？
或者能否让这个全局扫描（如果存在的话）的功能，可以被关闭？

**Comment by cyanzhong** [comment]
`包含此文件夹的App` 指的是 `包含此文件夹的脚本`？

在默认情况下，JSBox 只会索引 `scripts` 目录下的 `*.js` 文件，除非打开了索引全部文件的选项（在编辑器辅助选项里面）。

所以我怀疑这个性能问题并不是和索引有关，而是别的什么问题。请问你在 Pythonista 实践的时候，他可以做到迅速地打开吗？

**Comment by cyanzhong** [comment]
另外我还有一个疑惑的点是，这 100K 个文件，是否是平铺的放在了一个文件夹下面？有没有可以通过一些索引策略，让他们树状的分布在很多层文件夹里面？这可能是一个可以优化性能的点。

**Comment by Gandum2077** [comment]
`包含此文件夹的App`就是指`包含此文件夹的脚本`。
Pythonista在进行“新建文件”操作、“点击键盘上方+号选取图片”操作的时候，也会卡顿很久，特别是后面一个操作在我现在文件多到已经无法执行，Pythonista会一直卡住直到闪退。
但是Pythonista只要不去碰那个超级文件夹，其他操作都不受影响，可以正常的打开脚本、编辑脚本。  

我想即使树状的分布在很多层文件夹应该也不行，我当时测试的时候，就是把图片放在一个三级文件夹中（类似于`assets/image/a`），但是不只是打开`assets/image/a`会卡顿，打开`assets/image`和`assets`也会卡顿，不过打开其他文件夹，比如`scripts`，则不受影响。
尤其值得怀疑的是：当你打开某个文件夹，比如`assets`，那么JSBox就能够把`assets`底下的每个子文件夹下有多少文件显示出来，这怎么想都应该是执行了某种扫描之后的结果。

**Comment by Gandum2077** [comment]
关于`树状的分布在很多层文件夹`再补充一点：我当时是在一个文件夹中不断创建子文件夹，每个子文件夹放239张大图和239张小图，本来想创建1000个来测试的（总数大约500k），但是到700个文件夹就基本瘫痪了。所以可以说我的测试已经满足`树状的分布在很多层文件夹`这个条件。

**Comment by cyanzhong** [comment]
最新 TestFlight 版本中已经解决，下个版本上线这个改动。
