### ISSUE TITLE
“导入图片”功能在导入编辑过的图片时出现错误

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#10]
详情：点击右上角加号“导入图片”，如果选择的是在“图片”应用中曾经编辑过的图片，那么导入的将不是图片，而是一个叫做`Adjustments.plist`的文件。
此Bug在TF版和正式版1.57均可复现。

**Comment by cyanzhong** [comment]
Confirmed & Fixed.
