### ISSUE TITLE
关于小组件的cornerRadius的一些问题

### ISSUE THREAD

**Issue by dompling** [cyanzhong/jsbox-issues#101]
从 IOS14 的小组件文档中的属性可以看到 cornerRadius 这个适用于所有视图的属性。
但对于 vstack，和 hstack 应该都是支持的才对，但是实际的效果并没有支持。
本以为cornerRadius这个属性有问题，但是在 image上面却是支持的。
希望大佬能看看这个问题。

**Comment by cyanzhong** [comment]
我觉得这个可能不是问题 vstack 和 hstack, zstack 的本质不是控件，而是一个布局。

**Comment by dompling** [comment]
感谢您的解答，假如我想实现的是带渐变色圆形背景我应该用那种方式来实现呢？

**Comment by cyanzhong** [comment]
可以试一下用 color 这个组件，不过我不太确定。

**Comment by cyanzhong** [comment]
建议去 http://t.me/PinTG 问问最近做过小组件的朋友，因为这个不是 JSBox 本身的问题，先关掉。
