### ISSUE TITLE
修改菜单控件的色调闪退

### ISSUE THREAD

**Issue by xyranger** [cyanzhong/jsbox-issues#11]
版本：2.0.0（613）
系统及设备：iPhone XR（iOS13.3）
步骤：用UI编辑器新增菜单控件，修改色调属性（主要想修改对应label颜色和选中的label底部线条颜色），然后返回运行闪退。再次点击脚本应用一直闪退。
![image](https://user-images.githubusercontent.com/12688805/71226445-d5b6c880-2316-11ea-961a-d60c35de27c7.png)
![image](https://user-images.githubusercontent.com/12688805/71226449-da7b7c80-2316-11ea-9257-3d1eca6798ba.png)

顺便请问一下修改lable颜色和选中label底部线条颜色是否是修改色调属性。因为开发文档里面没有对应属性介绍，想用ui编辑器看看对应的是什么属性的。

**Comment by xyranger** [comment]
另外好像修改menu的边框颜色属性（borderColor:$color("clear") or borderWidth:0）没有生效。

**Comment by cyanzhong** [comment]
这个控件可能不支持那么多的自定义设置，不过闪退的问题我会调研一下，感谢反馈。

**Comment by cyanzhong** [comment]
闪退的问题已解决，请等待下个 Build。
