### ISSUE TITLE
内置编辑器使用rest语法问题

### ISSUE THREAD

**Issue by moemoechu** [cyanzhong/jsbox-issues#114]
内置编辑器使用rest语法后，代码自动提示会失效。
使用rest语法的代码运行是没有任何的问题。

![6A9B91D3-2394-40B8-87B0-916BCEE0F0C8](https://user-images.githubusercontent.com/6707029/139639854-e4275bb5-e40d-46a8-9cd9-946a5a22a056.jpeg)
![798BC77B-1F60-4620-B20B-BC66F6D1AA22](https://user-images.githubusercontent.com/6707029/139639858-11430973-5ce9-4ea0-9862-177b1ce6b9f7.jpeg)

**Comment by cyanzhong** [comment]
内置的 parser 没有更新到最新导致的，下个版本更新。
