### ISSUE TITLE
$sqlite中db.query这个方法，args使用非ascii字符，无法获得正确的sql结果

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#13]
在JSBox中使用$sqlite执行查询语句，如果args使用非ascii字符，有可能无法获得正确的sql结果（简单的SQL语句有时候能够执行成功，但是复杂的SQL语句几乎必然会出问题）

复现问题的最小DEMO：
首先数据库如下（一共只有一条测试用的数据）：

```
CREATE TABLE downloads (
	gid INTEGER,
	token TEXT,
	japanese_title TEXT
);
INSERT INTO downloads VALUES (1, 'sss', '太郎')
```

代码如下：

```
const sql0 = {
    clause: `SELECT DISTINCT gid||'_'||token
FROM downloads 
WHERE japanese_title like ?`,
    args: [
        "%郎%"
    ]
}

const sql1 = {
    clause: `SELECT DISTINCT gid||'_'||token 
FROM downloads 
WHERE japanese_title like "%郎%"`
}

function search(clause, args=null) {
    const db = $sqlite.open('assets/test.db');
    let rs
    if (args) {
        rs = db.query({
            sql: clause,
            args: args
        }).result
    } else {
        rs = db.query(clause).result;
    }
    const result = [];
    while (rs.next()) {
        result.push(rs.values)
    };
    rs.close();
    $sqlite.close(db);
    return result
}

const result0 = search(sql0.clause, args=sql0.args)
console.info(result0)    // 预期返回[]
const result1 = search(sql1.clause, args=sql1.args)
console.info(result1)    // 预期返回[{"gid||'_'||token":"1_sss"}]
```

可以看到，`sql1`就是将`sql0`的args手动拼接到SQL语句当中，但是sql1可以正确返回结果，所以这很可能是$sqlite模块对于args存在非ascii字符的情况处理不当。

**Comment by cyanzhong** [comment]
这是一个非常奇怪的 bug，因为 JSBox 实际上并不会对参数进行任何处理，不管是不是 ASCII 字符。只是将参数传给 libsqlite3，JSBox 自己可以说完全没有逻辑。

奇怪的地方是在于我直接用 libsqlite3 是不能复现这个问题的，但是加上 JavaScriptCore 就可以复现。我初步估计这个问题和线程切换有关系，不过还没有找到根本原因。

**Comment by cyanzhong** [comment]
这个问题非常麻烦，我深入研究之后发现，是因为 JavaScriptCore 无法正确持有 libsqlite3 返回的 C 指针，导致第一次调用 `next` 的时候就被告知 sqlite 的 statement 已经结束。

这个事情的背后是因为 libsqlite3 返回的句柄无法被延迟使用，所以在 native 将数据返回到 JavaScriptCore，JavaScriptCore 在调用 `next` 来调用 native 方法时，statement 已经被释放掉了。

完全解决这个问题可能需要话更多时间，所以在 Build 634 里面我修改了 db.query() 让他支持 handler 参数：

```js
db.query({
  sql: "SELECT * FROM User where age = ?",
  args: [28]
}, (rs, err) => {

});
```

这样不会出现线程切换引起的野指针问题，请先试一下这个 workaround。
