### ISSUE TITLE
对于label控件，如果宽度使用非整数，那么背景颜色可能无法完全填充控件

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#15]
详细描述：对于一个label控件，如果指定其frame.width为非整数，比如说1.78，那么背景颜色无法完全填充控件，会在右侧留下一条灰线，但是上下左都不受影响。

```
const size = {
   "width": 1.78,
   "height": 20
 }
$ui.render({
  views: [{
    type: "label",
    props: {
      frame: $rect(100, 100, size.width, size.height),
      bgcolor: $color("white")
    }
  }]
})
```
上述代码理论上应该会看上去一片纯白，但是实际上会出现一条灰线，如下图：
![gray line](https://i.imgur.com/yKr2lta.jpg)

这个bug的三个特点：
 1. 只有label控件存在这个问题；
2. 只有右侧存在这个问题；
3. 并不是所有小数都会出现，比如说48.1、48.2没问题，但是48.25就有问题，关于这一点，我怀疑是小数部分是0.25到0.49，以及0.75到0.95之间的数会出现这个问题。

**Comment by cyanzhong** [comment]
这个不是 bug，这是 iOS 的像素对齐问题。用 Auto Layout 的话 iOS 会自动为你处理这种问题。frame 的话你可以根据情况对 size 取整，例如使用 `Math.ceil(...)` 或 `Math.floor(...)`
