### ISSUE TITLE
可否为$prefs.open()增加回调事件？

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#17]
详细描述：希望$prefs.open()能够支持回调事件，以便能够在配置结束以后，对配置进行合法性检查，并可以进行一些完成配置以后才能进行的初始化操作。

附注：我想到一种替代性的方案：在$prefs.open()之后，开启循环不停的检查$ui.window是否有变化，在有变化以后退出循环。不知是不是目前的最优解。

**Comment by cyanzhong** [comment]
具体回调什么？

**Comment by Gandum2077** [comment]
我认为回调true即可，表示设置已经完成。

**Comment by cyanzhong** [comment]
所以你的意思是说用户完成设置之后，知道其回到了上个页面？

**Comment by Gandum2077** [comment]
是的

**Comment by cyanzhong** [comment]
Build 638 已添加回调函数
