### ISSUE TITLE
list控件是否存在某个属性，来判断是否列表中存在某一行处于左滑状态？

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#18]
详细描述：list控件添加props: actions以后，可以被左滑从而选择诸如“删除”、“分享”之类的操作。我已经发现swipeEnabled事件可以用于检测左滑事件是否发生（虽然它的本意不是如此），但是好像只能检测发生，不能检查是否被取消（即右滑回去）。
我想做一个aria2客户端，这个客户端会每隔1秒或数秒的刷新data以便监控aria2的状态。所以我希望能够在用户执行左滑操作之后，暂停刷新data，等到用户操作完成以后，再重新开始刷新。这需要一个能够判断是否列表中存在某一行处于左滑状态的属性，请问list控件是否有这么一个属性？

**Comment by cyanzhong** [comment]
可以增加这个属性，不过这种属性属于比较危险的。因为只能知道可见区域是不是有划出来的内容，这种逻辑是易碎的。

**Comment by Gandum2077** [comment]
原来如此。不过list控件无论是更新data，还是滚动，都会使得list取消左滑状态，而且似乎没有接口（至少没有JSBox接口）以编程方式触发左滑，应该很难在不可见区域出现。

**Comment by cyanzhong** [comment]
Build 638 已添加 `hasActiveAction`.
