### ISSUE TITLE
$file.copy是否能用于从iCloud Drive向JSBox目录拷贝文件或者目录？如果可以该如何操作？

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#19]
首先实测这样操作并不可以：
```
$file.copy({
  src: "drive://Code/test.txt",
  dst: "test.txt"
})
```
请问该如何操作才能在JSBox中从iCloud Drive向JSBox应用目录拷贝文件？

另外解释一下，1. 我想用拷贝，而不是读取再写入这种方法，是因为想利用APFS的特性，让重复文件不占用空间。 2. 在“文件”应用中可以拷贝到JSBox目录，但是因为目标是40多G的图片文件，所以在“文件”应用中拷贝时间非常长而且过程不可监测（测试了1万张图片，可以得知“文件”应用拷贝大量文件耗时很长），所以希望采用编程化的方式解决这个问题。

**Comment by cyanzhong** [comment]
好像可以支持，下个 Build。

**Comment by cyanzhong** [comment]
同样在 Build 659 支持。
