### ISSUE TITLE
$archiver.unzip存在连续使用会导致程序崩溃的bug

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#20]
$archiver.unzip连续的解压压缩包，会导致程序崩溃  

此问题有以下特点：
1. 必须是连续解压
2. 压缩包的文件体积必须在一定程度之上，太小无法复现此问题
3. 连续解压特定的数个压缩包，一定会运行到特定个数后崩溃，不具有随机性
4. 在不同的设备上，触发此Bug所需解压的个数不一样
5. 这个问题很可能与累计解压的文件体积有关，在我的测试中，我分别解压34MB、18.8MB、17.3MB的压缩包，分别在22次、41次、44次之后JSBox崩溃，累计体积为748MB、761.2MB、770.8MB
6. JSBox重启后，不会给出崩溃日志

以下为测试代码，这个测试需要在主目录添加一个叫做`t.zip`的测试压缩包，这个压缩包的体积不能太小（与压缩包的内容应该无关）

```javascript
const original = 't.zip'

// 文件夹初始化
if ($file.exists("temp")) {
    $file.delete("temp")
}
$file.mkdir("temp")


for (let i in [...Array(1000)]) {
    console.info(i)
    const dirname = "temp/" + i
    $file.mkdir(dirname)
    const success = await $archiver.unzip({
        file: $file.read(original),
        dest: dirname
    })
    console.info(success)
}

```
测试平台是build 655，iPad和iPhone均可复现此Bug

**Comment by Gandum2077** [comment]
另外当我汇报 issue#1 文件系统中大量文件导致JSBox卡顿的那个Bug的时候，35万张测试用的图片就是通过`$archiver.unzip`不停的解压缩来创建的。那时候可能没有这个Bug，否则的话那样操作应该是不行的。

**Comment by cyanzhong** [comment]
这个其实和 archiver 没关系，真正的原因是 load 了太多的 data 到内存。我在想实现 auto release pool，以及对 archiver 增加用路径来解压的机制。

**Comment by cyanzhong** [comment]
正在上传 Build 659，可以使用 `path: original` 取代你上述代码的 `file: $file.read(original)`，这个方式使用会极大减少内存使用。
