### ISSUE TITLE
文件夹中存在数量较多的文件，并且总体积比较大，那么打开这个文件夹会导致JSBox失去响应

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#21]
这个问题是我在执行转移文件操作时发现的，具体表现为：  
我将文件打包为1700个压缩包，这些压缩包总计大约40GB，放在同一个文件夹中。此时如果打开这个文件夹，那么JSBox就会失去响应（但是不会立即崩溃，而是一直卡死在那里）。  
个人推测，JSBox能够显示文件的大小，是不是因为在得到文件列表之后，执行了一个类似于list.forEach的操作去获取所有文件的大小？但是这个操作对于数量过多体积过大的文件，会失去响应。

**Comment by cyanzhong** [comment]
设置 -> 辅助编辑选项 -> 显示文件信息

**Comment by Gandum2077** [comment]
实测关闭“显示文件信息”这个选项之后，打开这个拥有1733个压缩包的文件夹后依然无响应。可能与此无关。

**Comment by cyanzhong** [comment]
测过别的 app 吗？

**Comment by Gandum2077** [comment]
别的App？是指Pythonista吗？如果是这个意思的话，那边没有这个问题，这些压缩包就是用Python shutil打包然后导入JSBox的

**Comment by Gandum2077** [comment]
写了一个DEMO，可以快速复现这个问题。  
这需要在主目录放置一个100MB的`t.zip`

```javascript
const original = 't.zip'

// 文件夹初始化
if ($file.exists("temp")) {
    $file.delete("temp")
}
$file.mkdir("temp")

// 拷贝1000遍
for (let i in [...Array(1000)]) {
    const success = $file.copy({
        src: original,
        dst: "temp/" + i + ".zip"
    })
    console.info(success, i)
}
```
如果只是拷贝100遍的话，打开文件夹在一段时间之后还能反应过来，拷贝1000遍就会完全失去响应

**Comment by cyanzhong** [comment]
注意到这个 bug 和之前那个表现是不一样的对吧，这个需要打开具体的那个文件夹才会出现是吗？

**Comment by Gandum2077** [comment]
`之前那个`是指[issue#1](https://github.com/cyanzhong/jsbox-issues/issues/21)的问题吗？如果是的话，那么答案是不一样，现在是一个新问题。
您可以试一下我上一条回复的DEMO，然后打开`temp`这个文件夹，就可以复现这个问题。

**Comment by cyanzhong** [comment]
Fixed in build 663
