### ISSUE TITLE
希望$text.decodeData支持编码kCFStringEncodingGB_18030_2000 = 0x0632

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#32]
$text.decodeData的encoding[参考文档](https://developer.apple.com/documentation/foundation/nsstringencoding)当中并没有关于中文的编码。
继续查阅文档，得知GBK需要的编码为CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingGB_18030_2000)，即0x0632，希望能够支持这种编码，以方便GBK转UTF-8。

**Comment by cyanzhong** [comment]
```js
CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingGB_18030_2000) = 2147485234;
```

这个运行出来的结果就是个常量，直接用这个数字应该就可以了。
