### ISSUE TITLE
希望“键盘符号”这个功能可以自定义顶层的那八个符号

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#33]
目前“键盘符号”功能确定了八个只能修改顺序，但是不能更改内容的符号放在顶层，即`$ () "" : , . + =`。
对于iPhone这可能是最优解。但是在iPad上，这八个符号中一大半在键盘上已经有了，使得重复的符号占据了宝贵的空间。所以希望能够自定义，把其他符号提到顶层用。

**Comment by cyanzhong** [comment]
实际上是可以改的，长按符号时的二级符号也是可以改的：

<img src='https://user-images.githubusercontent.com/6745066/75095446-bf0b4700-55cf-11ea-8887-e204867bfd9c.PNG' width='240px' /> <img src='https://user-images.githubusercontent.com/6745066/75095449-c2063780-55cf-11ea-9297-efafa92ab768.PNG' width='240px' />
