### ISSUE TITLE
在JSBox启动一段时间之后，使用动画链式调用，会先闪烁一帧结果，然后才开始播放动画

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#36]
动画链式调用存在一个问题：有时候会先闪烁一帧最终结果，然后才开始播放动画。
这个问题必须在JSBox启动一段时间之后才会出现，是可以复现的，而且重启JSBox问题就会消失。

**Comment by cyanzhong** [comment]
检查过，但 JSBox 应该没有做错什么。本质上 JSBox 只是直接调用 [JHChainableAnimations](https://github.com/jhurray/JHChainableAnimations)，而这个项目已经年久失修。

在我找到更好的替代方案之前，建议还是使用 `$ui.animate(...)`，或对其进行简单的封装。
