### ISSUE TITLE
关于如何实现视图自动刷新的一个设想

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#4]
既然view的事件可以通过一些操作来触发，比如tapped事件通过点击来触发，那么就意味着：只要连续不停的点击，就可以连续不停的触发tapped事件。
如果每1/60秒就点击一下，那么就可以一秒钟执行60次tapped事件绑定的函数，这不就是刷新吗？
所以有一个很简单的方法，就是——**可不可以推出一个无需任何操作就能触发的事件（唯一条件就是要出现在屏幕上）**，省略“点击”这个人为的动作，代之以每到预定的时间间隔就自动执行（update_interval可以在props中定义），如此一来，梦寐以求的视图自动刷新——`events: update`，就到手了！
```
update: function(sender) {
}
```

**Comment by Gandum2077** [comment]
这个问题我已经想到如何解决了：
在ready事件中，绑定一个永远执行的函数，隔update_interval就执行一次，即
```
ready: async function (sender) {
  while (true) {
    await $wait(update_interval)
   // ……
  }
}
```
现在只差临门一脚：如何检测view的可见性？比如说一个scroll上面排列着50子view，现在只有10个显示在屏幕上，有没有通用的方法，可以检测哪些在屏幕上？
毕竟Pythonista有`view.on_screen`这个属性，专门用于检测view的可见性，那么这应该也是一个iOS内置的方法吧？
完全体大概会像这样：
```
ready: async function (sender) {
  while (true) {
    await $wait(update_interval)
    if (sender.on_screen) {
      // ……
    }
  }
}
```

**Comment by Gandum2077** [comment]
整个方案见此DEMO：

https://gist.github.com/Gandum2077/d7b01a6011d063028e11cd575af3c87a

**Comment by cyanzhong** [comment]
这个问题我将关闭，与目前的 UI 架构完全没有关系，并且不是任何一个主流 UI 框架会做的事情。
