### ISSUE TITLE
$objc_release() may not work

### ISSUE THREAD

**Issue by isssuer** [cyanzhong/jsbox-issues#40]
Hello, after I run script [Keyboard Height Observer](https://gist.github.com/cyanzhong/edf112d045d22a4f6c769577445e4db7) once, every time I run any other scripts and there will be a keyboard height info shows in console with keyboard status changed, unless restart JSBox.
As I try, `$objc_release()` may not work. My app version is `2.7.0 (921)`.

**Comment by cyanzhong** [comment]
It may need to remove observer manually by calling:

```js
$objc("NSNotificationCenter").$defaultCenter().$removeObserver(observer);
```
