### ISSUE TITLE
内置的prettier对于最顶层是数组的json文件会出现错误

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#41]
对于一个最顶层是数组的json，例如
```json
[
  {
    "a": 1
  }
]
```
JSBox内置的prettier会将其变成
```
[
  {
    a: 1
  }
];
```
这是错误的。怀疑prettier将这样的json文件识别为js文件。

**Comment by cyanzhong** [comment]
这不是 bug，你的输入数据是一个 Object Literal 而不**只**是个 JSON。Prettier 默认行为是尽可能的去掉可以去掉的双引号，对于 Object Literal 而言这是没有问题的。

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBtAOlABF4mc7ogCGRSWAjPlgL6YC6IANCBAA4wCW0AzsqMQBOgiAHcACkIR8UxAG4ROAE2YgARoOJgA1nBgBlNls5QA5shiCArnBYALGAFsANgHU7neDyNg4+6Z6ccp4AnsjgPHwsJjxwgjDimqaOxMgAZsTOsSwAVjwAHgBCmjp6+sSOcAAyJnDpmdkgefn6JqbOcACKVhDw9Vm2IEaCsYLhasRqcM6qbIImMK7KMHbIABwADCxzELGummzhc3CjcnUsAI498InsMiQ8ALRQcHBKb6qCcFecX4nEyVSSAyAxYsUcnAs1kGPDaHW6vTqwIagxgkyWShWyAATCxLMROM42gBhCCOFLhKDQc4gKyxAAqkxkIMachsAEkoO9YPowPMOABBLn6GAhDr9WI0GhAA
