### ISSUE TITLE
tableViewCell 布局相关的建议

### ISSUE THREAD

**Issue by coo11** [cyanzhong/jsbox-issues#46]
1. 经过查阅，在列表视图中存在一个 BUG，屏幕旋转后，tableView 的 cell 视图的约束不起作用。
尝试后发现，在旋转后使用 `reloadData`，`setNeedsLayout` 和 `layoutIfNeeded` 等方法貌似无效。
现在希望钟老师可以在设置 template 时允许设置一个 `flex` 属性来解决问题：
```javascript
tamplate: {
    props: {
        frame: $rect(0, 0, 0, 0),
        flex: "WH"
    },
    views: [
    // ...
    ]
}
```

2. 根据 JSBox 文档中的定义，stackView 的子视图**写在 props 中**。
因此想尝试在 tableview 的 tamplate 中使用堆栈视图，这样一来可以灵活地自定义每个 cell 中的子视图数量，方便布局，但是并不起作用，希望钟老师可以允许在列表视图的 props 中这样定义：
```javascript
{
  tamplate: [
    {
      type: "stack",
      props: {
        id: "stackView",
        axis: stackViewAxis.horizontal
      },
      layout: $layout.fill
    }
  ],
  data: [
    {
      stackView: {
        stack: {
          views: [
            view1,
            view2
            //...
          ]
        }
      }
    }
  ]
};
```

**Comment by Gandum2077** [comment]
有个不成熟的建议，所有Cell都用静态Cell即可解决这两个问题，至于效率问题，只有几十上百行的话基本感受不到影响。

写了个小DEMO

![img](https://i.imgur.com/sRIUbKy.jpg)

**Comment by coo11** [comment]
的确不打算写太多行，不卡顿的话写成静态倒也不错。
现在想想可能是个伪需求。
谢谢建议！
