### ISSUE TITLE
能否为gallery控件增加一个属性，让其自带的UIPageControl可以隐藏？

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#47]
基于以下理由，希望能够隐藏gallery控件的UIPageControl
1. 这个控件能显示的数目太少，即使是iPad也只能显示十几个圆点，页数很多的情况下下面一排全是圆点，很不美观；
2. 颜色、布局等不能控制，存在和整体布局冲突的可能性，如果可以隐藏，那么可以自制分页指示器来使用；
3. 可以扩大gallery控件的使用范围，让gallery成为一个更加简单易用的分页scroll控件。

**Comment by cyanzhong** [comment]
Going to expose its `pageControl` property in the next build.
