### ISSUE TITLE
可否支持竖排的 label view

### ISSUE THREAD

**Issue by isssuer** [cyanzhong/jsbox-issues#5]
有个需求是竖排显示label，想实现一下却发现很麻烦。不知作者可否提供一下，并且可以设置
`$align.top`，`$align.bottom`之类

**Comment by cyanzhong** [comment]
我不能理解这个需求，什么是竖排？请清晰地描述你的需求。

**Comment by cyanzhong** [comment]
如果说的是文字从上往下显示的话，这不属于控件需要提供的功能，请关闭 issue。
