### ISSUE TITLE
$cache模块对于其存储的内容能否保证安全性？

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#50]
在JSBox上应该如何保存敏感信息？$cache能否胜任？

1. 对于某个脚本使用$cache.set存储的信息，其他脚本是否有方法取得(包括objc方法)？
2. 在未加密的iOS备份中是否可以取得？
3. 越狱后是否可以取得？

**Comment by cyanzhong** [comment]
JSBox uses [PINCache](https://github.com/pinterest/PINCache) for the $cache module, I don't think it's feasible for storing sensitive information.
