### ISSUE TITLE
是否有方法可以让JSBox下载和更新iCloud存在但是本机中尚不存在的文件？如果没有可否添加一个？

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#54]
我希望为脚本添加iCloud云同步功能，遇到了一些问题寻求帮助。

如果一个文件已经存在于iCloud，并且可以在官方的“文件”App中看到，但是此时右上角还有一个小箭头说明这个文件还没有被下载下来。  
对于这样的一个文件，JSBox是否有方法把它下载下来？

假如此文件叫做`test.db`，我知道此时对目标文件所在的文件夹使用`$file.list`，将可以看到一个叫做`.test.db.icloud`的文件，该如何让JSBox通知iCloud去下载此文件？

另外还有一个延续性的问题：假如`test.db`被更新了，该如何让JSBox通知iCloud去下载新版本？

**Comment by cyanzhong** [comment]
可以增加一个下载并获取 iCloud 文件的接口，但是知道更新这件事比较麻烦，建议尽可能主动去更新。

**Comment by cyanzhong** [comment]
下个 Build 增加 `$file.download(path)`
