### ISSUE TITLE
"双指缩放"功能与点击手势/事件存在冲突

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#58]
对于实现了双指缩放功能的image控件，如果为其再加上一个tapped事件，并且tapped事件实现的功能涉及到其他ui元素的更改，就会导致当image处于放大状态的时候，一旦点击则scroll.zoomScale会立刻变回原本状态（具体多少根据contentMode而定）。但是这个功能本来应该由双击来完成。

不一定要在image控件上添加，也可以在scroll上绑定UITapGestureRecognizer，或者在scroll的superView上添加，都可以复现这个问题。

有以下例子：
- 最典型的就是console.info()。只要打印任何东西，zoomScale立即变回原本状态，当然这个只能在debug模式下才能复现。
- $ui.toast。如果使用这个，那么可以zoomScale一直维持到toast消失，toast消失的那一刻zoomScale立即变回原本状态。
- 如果tapped事件的功能是添加一个控件，那么整个scroll都不能正常工作——zoomScale会不停的变回原本状态，整个scroll会不断闪动，即使tapped并未触发。

但是tapped事件并非不能使用，比如可以做一些运算，不涉及ui元素就没有问题。

```js
$ui.render({
  props: {
    title: ""
  },
  views: [
    {
      type: "scroll",
      props: {
        zoomEnabled: true,
        maxZoomScale: 3,
        doubleTapToZoom: true
      },
      views: [
        {
          type: "image",
          props: {
            userInteractionEnabled: true,
            src:
              "https://images.apple.com/v/ios/what-is/b/images/performance_large.jpg"
          },
          layout: $layout.fill,
          events: {
            tapped: sender => {
// 如果此时处于放大状态（即zoomScale > 1），那么只要使用了console，就会导致zoomScale立即变回1
              console.info(1);
// 不过有一些事情可以实现，比如把标题改一下，就不会触发这个问题
             // $ui.title = "title";
            }
          }
        }
      ],
      layout: $layout.fillSafeArea
    }
  ]
});


```

**Comment by cyanzhong** [comment]
有没有除了 console 也能触发这个 bug 的案例？

**Comment by cyanzhong** [comment]
修复在下个 Build 提供
