### ISSUE TITLE
希望为styledText的下划线和删除线增加更多样式

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#59]
通过删除线和下划线的不同样式，可以有效的提高信息密度，而且用于list和matrix的cell内，可以实现更加方便的布局。

尤其是希望为下划线增加以下两种样式：
- NSUnderlineStylePatternDot
- NSUnderlineStylePatternDash

**Comment by cyanzhong** [comment]
可能已经支持，只是文档没有体现，请尝试一下这些常量：

typedef NS_OPTIONS(NSInteger, NSUnderlineStyle) {
    NSUnderlineStyleNone                                    = 0x00,
    NSUnderlineStyleSingle                                  = 0x01,
    NSUnderlineStyleThick API_AVAILABLE(macos(10.0), ios(7.0))      = 0x02,
    NSUnderlineStyleDouble API_AVAILABLE(macos(10.0), ios(7.0))     = 0x09,

    NSUnderlineStylePatternSolid API_AVAILABLE(macos(10.0), ios(7.0))      = 0x0000,
    NSUnderlineStylePatternDot API_AVAILABLE(macos(10.0), ios(7.0))        = 0x0100,
    NSUnderlineStylePatternDash API_AVAILABLE(macos(10.0), ios(7.0))       = 0x0200,
    NSUnderlineStylePatternDashDot API_AVAILABLE(macos(10.0), ios(7.0))    = 0x0300,
    NSUnderlineStylePatternDashDotDot API_AVAILABLE(macos(10.0), ios(7.0)) = 0x0400,

    NSUnderlineStyleByWord API_AVAILABLE(macos(10.0), ios(7.0))            = 0x8000
} API_AVAILABLE(macos(10.0), ios(6.0));

文档我会做一个更新。

**Comment by cyanzhong** [comment]
iOS 这个 API 实在是有点难用，如果你想要 dot 的话，需要用 0x01 | 0x0100
