### ISSUE TITLE
能否给出某种方法，禁用图片缩放功能中的双击缩放功能，只保留双指缩放功能

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#6]
双击缩放功能严重影响点击效率，使得点击操作无法连续使用，希望能够给出禁用的方法。
在我的实际业务需求上，点击操作将会非常频繁，所以希望作者能够给一个禁用双击缩放的选项。或者将这两个功能分开，谢谢！

补充说明：视图同时拥有单指点击事件和双指点击事件，那么单指点击之后会有一段时间延时，才会触发单指点击事件，这让人很难受。而只有单指点击事件的话，是零延时的。

**Comment by cyanzhong** [comment]
`双击缩放功能严重影响点击效率`

你的论据在哪里？我可以增加这个选项，但是绝大部分图片浏览器都有这个手势。

请你务必给出理由。

**Comment by cyanzhong** [comment]
将增加 'doubleTapToZoom' 属性，默认 true。
