### ISSUE TITLE
ios14 运行长按菜单样例代码闪退

### ISSUE THREAD

**Issue by wpy23tl** [cyanzhong/jsbox-issues#65]
在13.5.1运行正常
$ui.render({
views: [
{
type: "button",
props: {
title: "Long Press!",
menu: {
title: "Context Menu",
items: [
{
title: "Title",
handler: sender => {}
}
]
}
},
layout: (make, view) => {
make.center.equalTo(view.super);
make.size.equalTo($size(120, 36));
}
}
]
});

报错日志
-[__NSDictionaryM _immutableCopy]: unrecognized selector sent to instance 0x283a70b80

**Comment by cyanzhong** [comment]
下个 Beta 修复
