### ISSUE TITLE
通过快捷指令运行jsbox脚本$delay失效

### ISSUE THREAD

**Issue by wpy23tl** [cyanzhong/jsbox-issues#68]
以下代码在jsbox主程序中能做到30秒后出现推送控件，但是通过快捷指令触发，如关闭勿扰或指定时间(ios14 去掉运行前询问选项)，会立即推送延时无效
var $notify= function(body)
{
    $push.schedule({
   
        body: body
      
      })

}

var heweatherNowData="";

function aa(){

    $http.get({ url: 'https://free-api.heweather.net/s6/weather/now?location=22.588837,113.957428&key=d49b3ea7031b489ebf9889ea465b909b' }).then(
        response => { 
          heweatherNowData = response.data;

})}

aa();

$delay(30, function() {
    $notify(JSON.stringify(heweatherNowData));
  });

**Comment by cyanzhong** [comment]
验证没有发现问题，不过不应该这样设置通知，应该立即设置通知，但是通知有延时。

而不是靠延时来立刻触发通知。
