### ISSUE TITLE
希望为scroll控件的willEndDragging事件加上第三个参数targetContentOffset

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#71]
看了很多ViewPager的开源实现，发现这个参数是必不可少的。通过这个参数可以得知scroll正在往哪个方向滚动，这样才能确定到底翻到第几页。

真心希望能够解决这个问题，这对于实现漫画阅读左右滑动翻页至关重要。

**Comment by cyanzhong** [comment]
下个版本：

其中 `target` 为滚动停下来时候的位置，可以通过返回一个 `$point` 进行覆盖：

```js
willEndDragging: function(sender, velocity, target) {
  return $point(0, 0);
}
```
