### ISSUE TITLE
$ui.menu的颜色在iPad和iPhone表现不一致

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#72]
在iPad上，$ui.menu在浅色模式下的颜色会随着JSBox主题色而改变；  
而在iPhone上，$ui.menu在浅色模式下的颜色并不会随着JSBox主题色而改变；

希望能够统一为不随JSBox主题色而改变，或者添加tintColor参数。

**Comment by cyanzhong** [comment]
已修复，下个版本。
