### ISSUE TITLE
调用接口获取不到响应头

### ISSUE THREAD

**Issue by wpy23tl** [cyanzhong/jsbox-issues#77]
![C71C520F1181565DCCEA977615592C6C](https://user-images.githubusercontent.com/5203048/89707024-5f4a0200-d99d-11ea-9689-a34417bb4fbb.png)

**Comment by wpy23tl** [comment]
想通过登录拿cookie的，发现response里是空的，又试着掉其他接口发现，里面也是空的。希望钟大看下

**Comment by cyanzhong** [comment]
应该是有的，只是 console 输出没有那么详细，试试：

```js
const {respons} = await $http.get(...)
```
