### ISSUE TITLE
是否存在一个判断是否运行在iPad分屏模式、并获取对应Window Size的API？

### ISSUE THREAD

**Issue by Gandum2077** [cyanzhong/jsbox-issues#8]
如果没有的话，希望能添加一下

需求是这样的，目前我正在研究Mansory布局，就是昨天那个在矩形中放置不定长标签的问题，我在网上已经搜索到了相关文章讨论这个问题：https://juejin.im/post/5afbf79d6fb9a07aa83eeac0
但是这里面依赖一个关键的判断条件就是`[UIScreen mainScreen].bounds.size.width`。
又因为，既然视图渲染的顺序是自底向上的，在渲染完成之前得不到上层view的frame，所以上层view的宽度也不能当作条件使用，那么我能想到的唯一方案就是通过获取window size然后手动计算，获取矩形应该有的宽度。
由于iPad有分屏模式，window size和screen size不一样，所以不能使用screen size。也就是说，这里需要window size。

**Comment by cyanzhong** [comment]
我只能说你又走在错误的方向上了，以及你引用的那篇文章真的很差。在 auto layout 布局里面使用一个具体的 `屏幕/window` 的 size，我不知道什么样的人会干出这种事来，这整个理解就已经完完全全的错了。

不过如果你真的需要的话，那么你可以这样拿到 window:

```js
const window = yourView.ocValue().$window().jsValue();
```

如果你真的想学习 iOS 里面的一些做法，我推荐 raywenderlich, nshipster, 和 swiftbysundell 等知名的资源。就目前而言你列出过的文章，都存在严重地一些误导，我不明白这些人为什么要写文章。

**Comment by cyanzhong** [comment]
为了你的方便，我会增加 .window 属性到 view 上。

**Comment by Gandum2077** [comment]
请问`yourView.ocValue().$window().jsValue();`里面的`yourView`代表什么？
测试了以下代码，得到的结果是空的对象
```
var imageview = {
   type: "image",
   props: {
     id: "image1",
     src: "https://images.apple.com/v/ios/what-is/b/images/performance_large.jpg",
     contentMode: 1
   },
   layout: function(make, view) {
     make.left.right.equalTo(0);
     make.centerY.equalTo(view.super);
     make.height.equalTo(320);
   }
 }

$ui.render({
  props: {
    id: "test",
    title: "Hello, World!"
  },
  views: [imageview]
});

console.info($("test").get("image1").ocValue().$window().jsValue())
// 结果为{}
```

**Comment by cyanzhong** [comment]
因为当前的 view 还没有 window，试下在 events: appeared 里面拿。

另外一个方法是拿当前 controller 的 view 的 window：

```js
const window = $ui.controller.ocValue().$view().$window().jsValue();
```

或者可以拿 UIWindow.keyWindow:

```js
const window = $objc("UIWindow").$keyWindow().jsValue();
```

**Comment by Gandum2077** [comment]
第二个方法没有延时，这应该是我想要的。
