### ISSUE TITLE
部分设备$server无法获取serverURL

### ISSUE THREAD

**Issue by ipuppet** [cyanzhong/jsbox-issues#80]
测试程序
```js
let server = $server.new()
let handler = {}
handler.filter = () => {
    // 全部使用data
    return "data"
}
handler.asyncResponse = async (request, completion) => {
    completion({
        type: "data",
        props: { html: "=====Request=====" }
    })
}
server.addHandler(handler)
let options = {
    port: 6060
}
server.start(options)
console.log(server)
console.log(server.serverURL.string)
$http.get({
    url: `http://${$device.wlanAddress}:6060`,
    handler: response => {
        console.log(response)
        server.stop()
    }
})
```

输出结果
![image](https://user-images.githubusercontent.com/37722993/91662743-f75b8700-eb16-11ea-9c73-4126d5f021c4.png)

将请求链接($http.get)改为`http://localhost:6060`，并注释`console.log(server.serverURL.string)`后可正常获取请求并打印。

更改之后获取请求的`remoteAddress`为`::1:55169`

**Comment by ipuppet** [comment]
估计是ipv6的问题，让他打印了网卡信息也是一大堆ipv6和最后一个ipv4的127.0.0.1，有什么办法切换到ipv4吗，或者其他的解决途径？

**Comment by cyanzhong** [comment]
一个猜想是不能获取的设备没有定位权限，尝试用 $location 接口获取下？

**Comment by ipuppet** [comment]
一直找不到人测试。。。
我自己试了一下关掉位置权限，`$location.available`输出`false`，依然可以正常获取`server.serverURL`

**Comment by ipuppet** [comment]
> 一个猜想是不能获取的设备没有定位权限，尝试用 $location 接口获取下？

刚才找那位不能获取`server.serverURL`的同学试了，他给了定位权限（`$location.available`输出true）

**Comment by ipuppet** [comment]
时隔一年又看到了这个issue
现在破案了，蜂窝网络造成的这个结果🤣🤣
