### ISSUE TITLE
为 CGContext 添加 CGContextDrawPath 方法

### ISSUE THREAD

**Issue by isssuer** [cyanzhong/jsbox-issues#81]
使用 canvas 画布绘制完闭合路径后，执行以下内容
```javascript
ctx.fillPath()
ctx.strokePath()
```
发现无法同时完成填充和描边。

查阅资料发现，可以通过以下任意一个方式实现：
- 为上面两个路径方法分别绘制一遍路径。
- 使用 `CGContextDrawPath`。

因为前者实际使用时有点麻烦，希望钟大可以添加一个 `ctx.drawPath` 方法方便使用。

**Comment by cyanzhong** [comment]
感谢反馈，下个 Beta。
