### ISSUE TITLE
colorAtPixel 接口问题

### ISSUE THREAD

**Issue by isssuer** [cyanzhong/jsbox-issues#83]
`colorAtPixel` 这个接口似乎无法返回首行各点 `$point(x, 0)` 正确的颜色值（首列的各点 `$point(0, y)` 没有问题）。

使用 Objective-C 的方法 `sd_colorAtPoint` 是正常的。

测试代码：
```javascript
const image = $image(
  "https://raw.githubusercontent.com/opencv/opencv/ee1e1ce377aa61ddea47a6c2114f99951153bb4f/samples/data/lena.jpg"
);
let i = 0;
while (i < 100) {
  const x = Math.round(Math.random() * image.size.width);
  const point = $point(x, 0);
  const a = image.colorAtPixel(point).hexCode;
  const b = image.ocValue().$sd__colorAtPoint(point).jsValue().hexCode;
  console.log(`(${x}, 0): ${a} ${b}`);
  i++;
}
```

**Comment by isssuer** [comment]
此外，我尝试在 JSBox 中遍历图片的各点并对每个点的颜色值进行处理，会经常出现卡死崩溃的情况。可以的话，想请教一下钟大如何处理。

**Comment by cyanzhong** [comment]
第一个问题，我会内部换到用 SDWebImage 的实现。

第二个问题，最好附上一个例子？

**Comment by isssuer** [comment]
[安装链接](https://xteko.com/redir?name=trimImage&url=https%3A%2F%2Fgithub.com%2Fisssuer%2FMyScript%2Fblob%2Fmaster%2FtrimImage.box%3Fraw%3Dtrue)

**Comment by cyanzhong** [comment]
针对第一个问题，请试试最新的 Beta

**Comment by isssuer** [comment]
更新：
    
针对第二个问题所给出的例子，查阅资料改用定义 C 函数，使用 CGContext 实现。
    
但是到最后获取 Bitmap 上任意一点颜色值这步：

```Objective-C
//Objective-C
unsigned char *bitmapData = malloc(bitmapBytesCount);
NSInteger imageAlpha, imageRed, imageGreen, imageBlue;
// ....
//At point (0, 0):
imageAlpha  = bitmapData[0];
imageRed    = bitmapData[1];
imageGreen  = bitmapData[2];
imageBlue   = bitmapData[3];
```

在 JSBox 中貌似无法做到：
 
```Javascript
const bitmapData = $malloc(bitmapBytesCount)
// ....
console.log(bitmapData) // { "__clsName": "29", "__obj": "<$29>" }
````

请教一下钟大，这个 bitmapData 有什么办法获取任意一点的 A, R, G, B。

**Comment by cyanzhong** [comment]
`bitmapData` 的来源是什么？我可能需要一个更详细一点的 issue 来评估 JSBox 需要做些什么。@isssuer 方便重开一个 issue 么？这个 issue 混合了两个问题，不太好追踪。
