### ISSUE TITLE
menu控件导致的闪退

### ISSUE THREAD

**Issue by szq998** [cyanzhong/jsbox-issues#84]
对于一个打开了dynamicWidth的menu控件，增加其items中的项目，随后将index指向新增加的项目，会导致闪退。
这个index对于修改前的items是越界的，但对于修改后的items没有越界。
![86A3E830-2C1F-4695-8D54-80D9C1769CA1](https://user-images.githubusercontent.com/38434148/93272291-bdada000-f7e7-11ea-8bfc-677e481b5eb9.jpeg)

比如，对于这个menu控件，其items中有两个项目
```
{
  type: "menu",
  props:{
    items: ["0", "1"],
    dynamicWidth: true,
    frame: $rect(0, 0, 100, 40)
  }
}
```

现在试图增加一个item，并将index指向新增的项目，app就会闪退

```
$("menu").items = ["0", "1", "2"]
$("menu").index = 2
```

但如果加一个延迟，就不会闪退
```
$("menu").items = ["0", "1", "2"]
$delay(0.1, () => {
  $("menu").index = 2
})
```

将dynamicWidth设为false也不会触发这个bug。

iPad和iPhone都有这情况，系统都是iOS14，JSBOX也更新到了App Store中的最新版。

**Comment by cyanzhong** [comment]
这可能是因为 items 的设置是异步的，我会检查下。

**Comment by cyanzhong** [comment]
已解决，请等待下个 Beta，感谢反馈。
