### ISSUE TITLE
JSBox 使用 C 函数获取的 BitmapData 如何操作

### ISSUE THREAD

**Issue by isssuer** [cyanzhong/jsbox-issues#87]
之前在 #83 提出了读取图像位图数据的需求，然后通过定义 C 函数 `CGBitmapContextCreate` 指向 CGContext 在内存中的二进制存储的数组。
但是似乎无法利用目前 JSBox 中给出的接口获取数组对应的 RGBA 数据。

https://gist.github.com/isssuer/a555e4d61d0eb7f09aef2a85b231994d

这个 Gist 是我根据 [ImageTrim](https://github.com/cameronehrlich/ImageTrim/blob/master/ImageTrim/UIImage%2BImageTrim.m) 这个项目写的代码，请教一下钟老师这个 `bitmapData` 该如何进行处理？还是需要在 JSBox 中封装好才能使用，谢谢！

**Comment by cyanzhong** [comment]
@isssuer 你好，除了遍历所有的 RGBA 值，还有没有什么需求？我想直接封装一个获取二维数组的方法可能更简单。

**Comment by cyanzhong** [comment]
很抱歉我决定关掉这个 issue，原因是用 UIImage 相关的方法来处理，性能实在是太差了。一张截图需要遍历几十万个点，测试下来基本是不能接受的性能。

**Comment by isssuer** [comment]
感谢，是我想当然了。
