### ISSUE TITLE
日历和提醒事项接口需求

### ISSUE THREAD

**Issue by ipuppet** [cyanzhong/jsbox-issues#88]
1. 希望日历接口能获取到在日历中设置的颜色。

2. 提醒事项接口在某些情况下无法获取alarmDate：
当只设置了日期而未设置时间时无法获取

如图：
![photo_2020-10-12_21-39-50](https://user-images.githubusercontent.com/37722993/95753809-b8535080-0cd4-11eb-93a0-ef34d8485667.jpg)

**Comment by cyanzhong** [comment]
1. 应该可以添加
2. 只设置了日期应该就是没有 alarm?

**Comment by ipuppet** [comment]
只设置了日期的话应该如何获取到设置的日期？

**Comment by cyanzhong** [comment]
这个我也得关了，刚刚在调查另一个 issue 的时候确认了，苹果没有提供进一步的接口。
