### ISSUE TITLE
关于JSBox UI的一个小建议

### ISSUE THREAD

**Issue by kadefor** [cyanzhong/jsbox-issues#9]
图1：
![FCA374F4-0B53-4616-89F1-9A5D5A7544BA](https://user-images.githubusercontent.com/1145279/70637118-a7c7e900-1c71-11ea-8ae9-0a4f9e718cfa.png)

图2:
![DAC577A4-7A04-428B-AA5B-7DA2BFE7B8AA](https://user-images.githubusercontent.com/1145279/70637151-b910f580-1c71-11ea-9cff-2a6e333895fb.jpeg)

**当前**：“图1”中分类名称和“分类管理”排列得太整齐了，一眼看去感觉没有其他分类了。

**期望**：如果是“图2”标记的那样显示的话，对初次使用JSBox的用户可能会直观一些。

**环境**：iPhone 6s Plus, iOS 13.2.3, JSBox 1.56.0 (586)

**注**：其他环境未能测试

**Comment by cyanzhong** [comment]
考虑到一些因素，决定通过闪一下滚动条来暗示可以滚动。
