### ISSUE TITLE
jsbox 计划任务需求

### ISSUE THREAD

**Issue by snycg** [cyanzhong/jsbox-issues#91]
jsbox现有的计划任务都需要点击通知来执行脚本，能否通过定位权限（如OffScreen、足迹APP）保持jsbox在后台运行，同时使用cron表达式设定执行时间，达到后台自动执行脚本的效果，类似于Loon、Quantumult X和Surge的脚本功能。

**Comment by cyanzhong** [comment]
不能。您列举的这几个 app，要么是强依赖定位，要么是通过 NE 扩展实现的后台。

有类似的需求，请直接使用您列举的应用。
