### ISSUE TITLE
$imagekit.concatenate 的问题

### ISSUE THREAD

**Issue by DiamondI** [cyanzhong/jsbox-issues#96]
之前在JSBox的论坛里已经发了一个帖子了，不过后来看到说建议把issue放在这里，所以在这里也重新描述一下。

Link to forum: [https://jsboxbbs.com/d/1172-imagekit-concatenate](https://jsboxbbs.com/d/1172-imagekit-concatenate)

## 环境

iOS版本：14.2
设备：iPhone SE
JSBox版本：2.13.0(1171)

### 尝试1

```javascript
$photo.fetch({
    count: 2,
    handler: function(images) {
        const output = $imagekit.concatenate(images, 10, 0);
        $quicklook.open({image: output});
    }
  })
```

结果：显示“文件 数据”，并没有可见的图片显示，或者说打开的图片是格式异常的。

### 尝试二

```javascript
$photo.fetch({
    count: 2,
    handler: function(images) {
        //这里只放了一张图片
        const output = $imagekit.concatenate([images[0]], 10, 0);
        $quicklook.open({image: output});
    }
  })
```

结果：该图片被正常打开。

## 尝试结论

$imagekit.concatenate 的表现与预期不符

**Comment by cyanzhong** [comment]
已修复，等下个测试版。
