### ISSUE TITLE
Shortcut call to Nodejs

### ISSUE THREAD

**Issue by Wsine** [cyanzhong/jsbox-issues#97]
我发现Jsbox里面的NodeJS运行时与JsBox运行时被Shortcut应用调用的时候不太相同。

我现在的需求是通过shortcut访问 jsbox 里面的一个nodejs运行时的script，script需要获取输入并返回输出。

问题1: script无法debug获取的输入

类似 jsbox 上面的教程，我使用`query = $context.query`获取输入，但是由于是shortcut调用jsbox，无法看到console的输出结果，因此无法debug获取的输入是否正确

问题2: script无法终止当前script的运行

类似 jsbox 上面的教程，使用`$app.close()`和`$context.close()`的时候，没有对应的object或方法, 使用`process.exit()`可以看到script报错但快速执行退出

请问正确的终止方式是什么？

问题3: script无法返回输出给shortcut

类似 jsbox 上面的教程，使用`$intents.finish()`方法的时候，显示没有对应的object或方法

请问如何正确的编写shortcut和nodejs之间的交互？ 感谢

**Comment by cyanzhong** [comment]
Shortcuts 目前不支持运行 Node.js 的代码。
