### ISSUE TITLE
node-red under jsbox?

### ISSUE THREAD

**Issue by ifuchs** [cyanzhong/jsbox-issues#98]
Is it possible to install and run node-red (https://nodered.org/) under jsbox?

**Comment by cyanzhong** [comment]
Sorry for the late response.

The first look from my perspective, it seems not feasible since there're many build scripts, but I am interested in if we could bundle it to browsers.

Another problem is that the Web UI is not very good on mobile devices.

**Comment by ifuchs** [comment]
That’s too bad.
Thanks,
Ira
