### ISSUE TITLE
两个不同的 JSBOX 应用均使用「网页」控件会造成冲突

### ISSUE THREAD

**Issue by ImSingee** [cyanzhong/jsbox-issues#99]
对于单一的应用：第一次进入应用时不会触发网页的重新加载，第二次成功触发

对于两个同时使用了「网页」控件的应用：第一次切换应用时不会触发网页的重新加载（例如从 APP1 切换到 APP2 会发现这时的网页还是 APP1 的），第二次切换变成正常

**Comment by cyanzhong** [comment]
我之前碰到过几次，不过我现在在最新的版本无法复现，如果下个测试版还碰到，请提供一个案例，先关闭。
